# Use Debezium's latest Kafka Connect base image
FROM debezium/connect:2.7.3.Final

# Download and install the Debezium SQL Server connector
RUN curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/2.2.0.Final/debezium-connector-sqlserver-2.2.0.Final-plugin.tar.gz \
    | tar -xz -C /kafka/connect

# Download and install the Confluent JDBC Sink Connector JAR file
RUN curl -L https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.4.0/kafka-connect-jdbc-10.4.0.jar \
    -o /kafka/connect/kafka-connect-jdbc-10.4.0.jar

# Download and install the PostgreSQL JDBC Driver for the JDBC Sink Connector
RUN curl -L https://jdbc.postgresql.org/download/postgresql-42.7.4.jar \
    -o /kafka/connect/postgresql-42.7.4.jar